web:
  build: ./nginx-php
  ports:
    - "8080:80"
  links:
    - db
  volumes:
    - .:/usr/share/nginx/html
  environment:
    TEMPLATE_NGINX_HTML: 0
    ERRORS: 1
db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: rpassword
    MYSQL_DATABASE: wordpress
    MYSQL_USER: user
    MYSQL_PASSWORD: pass
